-- backup.sql
USE theatre_db;

-- Drop old backups
DROP TABLE IF EXISTS bak_TICKET_AUDIT;
DROP TABLE IF EXISTS bak_TICKET;
DROP TABLE IF EXISTS bak_SEAT;
DROP TABLE IF EXISTS bak_DISCOUNT;
DROP TABLE IF EXISTS bak_CUSTOMER;
DROP TABLE IF EXISTS bak_SHOWTIME;
DROP TABLE IF EXISTS bak_SEAT_TYPE;
DROP TABLE IF EXISTS bak_MOVIE;
DROP TABLE IF EXISTS bak_AUDITORIUM;
DROP TABLE IF EXISTS bak_THEATRE;

-- Recreate backup tables
CREATE TABLE bak_THEATRE       LIKE THEATRE;
CREATE TABLE bak_AUDITORIUM    LIKE AUDITORIUM;
CREATE TABLE bak_MOVIE         LIKE MOVIE;
CREATE TABLE bak_SEAT_TYPE     LIKE SEAT_TYPE;
CREATE TABLE bak_SHOWTIME      LIKE SHOWTIME;
CREATE TABLE bak_CUSTOMER      LIKE CUSTOMER;
CREATE TABLE bak_DISCOUNT      LIKE DISCOUNT;
CREATE TABLE bak_SEAT          LIKE SEAT;
CREATE TABLE bak_TICKET        LIKE TICKET;
CREATE TABLE bak_TICKET_AUDIT  LIKE TICKET_AUDIT;

-- Copy data
INSERT INTO bak_THEATRE       SELECT * FROM THEATRE;
INSERT INTO bak_AUDITORIUM    SELECT * FROM AUDITORIUM;
INSERT INTO bak_MOVIE         SELECT * FROM MOVIE;
INSERT INTO bak_SEAT_TYPE     SELECT * FROM SEAT_TYPE;
INSERT INTO bak_SHOWTIME      SELECT * FROM SHOWTIME;
INSERT INTO bak_CUSTOMER      SELECT * FROM CUSTOMER;
INSERT INTO bak_DISCOUNT      SELECT * FROM DISCOUNT;
INSERT INTO bak_SEAT          SELECT * FROM SEAT;
INSERT INTO bak_TICKET        SELECT * FROM TICKET;
INSERT INTO bak_TICKET_AUDIT  SELECT * FROM TICKET_AUDIT;
